name: a_news_app
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  shared_preferences: ^2.2.2
  http: ^0.13.4
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  provider: ^6.0.5
  intl: ^0.18.0
  get_it: ^7.2.0
  smooth_page_indicator: ^1.1.0
  video_player: ^2.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.3

flutter_native_splash:
  color: "#000000"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - images/
flutter_intl:
  enabled: true
  class_name: S